name: MySQL Installation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
